### ISSUE TITLE
Instructor Feedback - Week 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jvjohnson1/TheFortress#1]
Just so it doesn't fall off the radar for week 2 deliverables:

- [ ] Add a README.md and begin documenting your project problem statement/goal.
- [ ] Add a timeLog.md and then enter your time log entries from Week 1 and 2. If you prefer, you may choose to write journal entries to document your progress, problems solved, key learning points, and anything else you find useful to track. You should track all time spent on Ent Java work outside of class, not just indie project work.

**Comment by jvjohnson1** [comment]
It should be there - I'll push again before office hour.  Still planning to "come" at 4:45, when I log off work.

**Comment by jvjohnson1** [comment]
I think everything is correct now.  Let me know if I still need to fix anything.

**Comment by pawaitemadisoncollege** [comment]
Looks good. You can close this.
