### ISSUE TITLE
Reminder: fix formatting of design documents

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jvjohnson1/TheFortress#2]
The following need format fixes to improve readability in GitHub:
- [x] ApplicationFlow.md
- [x] ProjectPlan.md
- [x] TimeLog.md
- [x] UserStories.md

**Comment by jvjohnson1** [comment]
I followed the link you provided on Slack, and modified one file as a test.  (I choose ProjectPlan.md)  However, it came up on GitHub looking as bad as before.

**Comment by pawaitemadisoncollege** [comment]
It seems like you are working towards an unordered list?

Compare your code to the example github markdown example. What is different? 

Your code: 
<img width="1680" alt="Screen Shot 2020-09-27 at 7 49 27 AM" src="https://user-images.githubusercontent.com/13874466/94365383-1c9bd080-0096-11eb-8b3c-6337163e35f5.png">

Working lists from the github markdown reference:
<img width="709" alt="Screen Shot 2020-09-27 at 7 48 58 AM" src="https://user-images.githubusercontent.com/13874466/94365389-28879280-0096-11eb-8bb2-a35ed31bd6ab.png">

**Comment by jvjohnson1** [comment]
Fixed it, but spent way to much time, making it unlikely I will finish this week's work by Wednesday.  You want us to figure it out ourselves with only small hints, but we need a more efficient way of doing that.  I think that should be part of  teaching programming, maybe late in the first semester when the last project has some size.  By the third term we should be effective problem solvers, without the kind of stress I had this week - and last spring.

**Comment by pawaitemadisoncollege** [comment]
This looks good now @jvjohnson1 .

I'm sorry that markdown was frustrating for you. I thought the screenshots above showed the difference, which was   missing a space between the stars and the text.  Was that difficult for you to see in the screenshot format above? How could I have communicated that better?

You can close this up whenever you like!

**Comment by jvjohnson1** [comment]
The struggle was that there were numbers and sometimes letters after the items in the example, and I thought that meant those were required.  Plus, I kept trying to find a way to put and * in the text  (does markdown have an escape character?) so I could show was is MVP.

**Comment by pawaitemadisoncollege** [comment]
No need to escape it - just put the star at the end of the line. It’s the * at the beginning of a line, followed by a space that denotes it as a bullet.

Here are my demo repo user stories with MVP stories marked with a *.

https://github.com/mad-java-ent-f20/FatBikeTrailReports/blob/master/DesignDocuments/userStories.md

On Sep 27, 2020, at 8:41 PM, jvjohnson1 <notifications@github.com> wrote:



The struggle was that there were numbers and sometimes letters after the items in the example, and I thought that meant those were required. Plus, I kept trying to find a way to put and * in the text (does markdown have an escape character?) so I could show was is MVP.
