### ISSUE TITLE
Application question

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jvjohnson1/TheFortress#3]
Are you expecting that a person who hacks into the site reports that "success" somehow? That sort of hacking or testing seems central to your application's purpose.  What do you think about adding a user story or stories for this?

**Comment by jvjohnson1** [comment]
Fixed this problem in documentation by adding to additional user stories at the end of the "hacker" section

**Comment by pawaitemadisoncollege** [comment]
Looks good! 

One more question with regard to the user stories. Will a higher rank user be able to perform the tasks a lower rank user can perform? For example, can a Lieutenant or Captain also do the things a private can do such as:

- View my assigned duties
- View my personal data
- View issued equipment
- Report equipment missing or damaged
- Report duties complete
?

**Comment by jvjohnson1** [comment]
No. In real life they would, but they would be assigned duties by a higher ranking officer (like a Major) and report back to the same.  
Remember that this is a secure coding demonstration with a military theme, not a command and control simulation.  With no ranks above Captain included, it's hard to apply those cases.  Sure, the Captain could assign duties and issue equipment to a Lieutenant, and the Lieutenant could report back as applicable, but it wouldn't contribute to the primary purpose.  Let's include those as possible add-ons, but not in MVP.

**Comment by jvjohnson1** [comment]
Forgot to close this one weeks ago.
